const baseItens = [
  { code: "001", name: "Açúcar", unit: "kg" },
  { code: "002", name: "Farinha de Trigo", unit: "kg" },
  { code: "003", name: "Ovo", unit: "un" },
  { code: "004", name: "Sal", unit: "kg" },
  { code: "101", name: "Fermento Biológico", unit: "g" },
  { code: "102", name: "Leite em Pó", unit: "kg" },
  { code: "103", name: "Manteiga", unit: "kg" },
  { code: "201", name: "Chocolate em Pó", unit: "kg" },
  { code: "202", name: "Creme de Leite", unit: "L" },
  { code: "203", name: "Baunilha", unit: "ml" },
  { code: "204", name: "Açúcar Mascavo", unit: "kg" },
  { code: "301", name: "Leite Condensado", unit: "L" },
  { code: "302", name: "Corante Alimentício", unit: "ml" },
  { code: "401", name: "Tomate", unit: "kg" },
  { code: "402", name: "Cebola", unit: "kg" },
  { code: "403", name: "Azeite de Oliva", unit: "L" },
  { code: "404", name: "Alho", unit: "kg" },
  { code: "501", name: "Queijo Mussarela", unit: "kg" },
  { code: "502", name: "Molho de Tomate", unit: "L" },
  { code: "503", name: "Calabresa", unit: "kg" },
  { code: "601", name: "Arroz", unit: "kg" },
  { code: "602", name: "Feijão", unit: "kg" },
  { code: "603", name: "Óleo de Soja", unit: "L" },
  { code: "604", name: "Macarrão", unit: "kg" },
  { code: "701", name: "Carne Bovina", unit: "kg" },
  { code: "702", name: "Frango", unit: "kg" },
  { code: "703", name: "Batata", unit: "kg" },
];
