const listaBruna = [
  { code: "120010", name: "ACUCAR", unit: "KG" },
  { code: "121288", name: "AMEIXA SECA", unit: "KG" },
  { code: "120086", name: "AMENDOIM", unit: "KG" },
  { code: "120063", name: "CANELA", unit: "UN" },
  { code: "33039", name: "CEREJA", unit: "KG" },
  { code: "122834", name: "CHOCOLATE BARRA MEIO AMARGO", unit: "UN" },
  { code: "111702", name: "CHOCOLATE EM BARRA BRANCO", unit: "UN" },
  { code: "120013", name: "CHOCOLATE EM PO", unit: "UN" },
  { code: "55826", name: "COCO SECO PRODUCAO", unit: "UN" },
  { code: "120200", name: "CREME DE GOIABA", unit: "KG" },
  { code: "120047", name: "CREME DE LEITE", unit: "UN" },
  { code: "120062", name: "DOCE DE LEITE", unit: "KG" },
  { code: "120423", name: "FARINHA DE TRIGO", unit: "KG" },
  { code: "33428", name: "FERMENTO EM QUIMICO (BOLO)", unit: "KG" },
  { code: "120698", name: "FLOCAO DE MILHO", unit: "KG" },
  { code: "120093", name: "GOIABADA", unit: "KG" },
  { code: "120060", name: "GRANULADO", unit: "UN" },
  { code: "124785", name: "HORTI BABANA PRATA", unit: "KG" },
  { code: "111175", name: "HORTI MARACUJA", unit: "KG" },
  { code: "120087", name: "HORTI MORANGO", unit: "KG" },
  { code: "6873", name: "HORTI UVA", unit: "KG" },
  { code: "120046", name: "LEITE CONDENSADO", unit: "KG" },
  { code: "120240", name: "LEITE UHT", unit: "L" },
  { code: "119149", name: "MARGARINA VEGETAL", unit: "KG" },
  { code: "103244", name: "MASSA DE MACAXEIRA", unit: "KG" },
  { code: "56298", name: "MASSA DE PUBA", unit: "KG" },
  { code: "120024", name: "OLEO DE SOJA", unit: "LT" },
  { code: "113901", name: "OVO", unit: "UN" },
  { code: "120246", name: "QUEIJO PARMESAO RALADO", unit: "KG" },
  { code: "125523", name: "REFRESCO EM PO LIMAO", unit: "UN" },
  { code: "120704", name: "REFRESCO EM PO MARACUJA", unit: "UN" },
  { code: "125526", name: "REFRESCO EM PO MORANGO", unit: "UN" },
];
