const listaEduardo = [
  { code: "120033", name: "CALABRESA", unit: "KG" },
  { code: "120217", name: "CARNE DE HAMBURGUER", unit: "UN" },
  { code: "111347", name: "CREME RECHEIO", unit: "KG" },
  { code: "120423", name: "FARINHA DE TRIGO", unit: "KG" },
  { code: "35491", name: "MARGARINA FOLHADA", unit: "KG" },
  { code: "119149", name: "MARGARINA VEGETAL", unit: "KG" },
  { code: "120024", name: "OLEO DE SOJA", unit: "UN" },
  { code: "113901", name: "OVO", unit: "UN" },
  { code: "3186", name: "PRESUNTO", unit: "KG" },
  { code: "120051", name: "QUEIJO CATUPIRY", unit: "KG" },
  { code: "2318", name: "QUEIJO COALHO PRODUÇAO", unit: "KG" },
  { code: "120049", name: "QUEIJO MUSSARELA", unit: "KG" },
  { code: "119180", name: "QUEIJO PRATO", unit: "KG" },
  { code: "125617", name: "RECHEIO DE CARNE", unit: "KG" },
  { code: "125616", name: "RECHEIO DE FRANGO", unit: "KG" },
  { code: "120025", name: "SALSICHA", unit: "KG" },
];
