const listaPadaria = [
  { code: "120010", name: "ACUCAR", unit: "KG" },
  { code: "120090", name: "AMIDO DE MILHO", unit: "KG" },
  { code: "45506", name: "ANTIMORFO", unit: "KG" },
  { code: "120103", name: "CACHACA PITU", unit: "LT" },
  { code: "120013", name: "CHOCOLATE EM PO", unit: "UN" },
  { code: "55826", name: "COCO SECO PRODUCAO", unit: "UN" },
  { code: "120055", name: "CORAGEMA", unit: "UN" },
  { code: "120200", name: "CREME DE GOIABA", unit: "KG" },
  { code: "119125", name: "EMULSIFICANTE", unit: "LT" },
  { code: "120423", name: "FARINHA DE TRIGO", unit: "KG" },
  { code: "2790", name: "FARINHA DE TRIGO INTEGRAL", unit: "KG" },
  { code: "120092", name: "FERMENTO BIOLOGICO", unit: "KG" },
  { code: "33428", name: "FERMENTO EM QUIMICO", unit: "KG" },
  { code: "120698", name: "FLOCAO DE MILHO", unit: "KG" },
  { code: "33626", name: "FUBA DE MILHO", unit: "KG" },
  { code: "108339", name: "GELO PACOTE KG", unit: "UN" },
  { code: "33671", name: "GERGELIM", unit: "KG" },
  { code: "120093", name: "GOIABADA", unit: "KG" },
  { code: "120031", name: "HORTI CENOURA", unit: "KG" },
  { code: "120046", name: "LEITE CONDENSADO", unit: "KG" },
  { code: "120439", name: "LEITE EM PO", unit: "KG" },
  { code: "120240", name: "LEITE UHT", unit: "LT" },
  { code: "119149", name: "MARGARINA VEGETAL", unit: "KG" },
  { code: "120101", name: "MASSA PAO SEMI ITALIANO", unit: "KG" },
  { code: "120095", name: "MELHORADOR", unit: "KG" },
  { code: "119912", name: "MISTURA P/PAO AUSTRALIANO KG PRODUCAO", unit: "KG" },
  { code什么是: "111219", name: "MISTURA PAO MULTIGRAOS LEVIS", unit: "KG" },
  { code: "120024", name: "OLEO DE SOJA", unit: "UN" },
  { code: "113901", name: "OVO", unit: "UN" },
  { code: "120246", name: "QUEIJO PARMESAO RALADO", unit: "KG" },
  { code: "119180", name: "QUEIJO PRATO", unit: "KG" },
  { code: "3292", name: "SAL", unit: "UN" },
  { code: "19378", name: "UVA PASSAS", unit: "KG" },
  { code: "122730", name: "VINHO", unit: "UN" },
];
