const listaFernando = [
  { code: "32711", name: "AZEITONA", unit: "KG" },
  { code: "120035", name: "CALDO DE CARNE", unit: "UN" },
  { code: "20107", name: "CALDO DE GALINHA", unit: "UN" },
  { code: "45018", name: "CAMARAO PRA EMPANADO", unit: "KG" },
  { code: "120043", name: "COLORAL (CORANTE)", unit: "KG" },
  { code: "120047", name: "CREME DE LEITE", unit: "UN" },
  { code: "120020", name: "CUMINHO PRODUÇAO", unit: "KG" },
  { code: "120423", name: "FARINHA DE TRIGO", unit: "KG" },
  { code: "115423", name: "FARINHA PANKO", unit: "KG" },
  { code: "120040", name: "FILE DE PEITO DE FRANGO", unit: "KG" },
  { code: "120199", name: "HORTI ALFACE", unit: "UN" },
  { code: "120018", name: "HORTI", unit: "KG" },
  { code: "120021", name: "HORTI", unit: "KG" },
  { code: "120028", name: "HORTI CEBOLINHA", unit: "UN" },
  { code: "120031", name: "HORTI CENOURA", unit: "KG" },
  { code: "113987", name: "HORTI HORTELA UND", unit: "KG" },
  { code: "34111", name: "HORTI SALSA", unit: "UN" },
  { code: "120240", name: "LEITE UHT", unit: "L" },
  { code: "119149", name: "MARGARINA VEGETAL", unit: "KG" },
  { code: "120024", name: "OLEO DE SOJA", unit: "LT" },
  { code: "113901", name: "OVO", unit: "UN" },
  { code: "126254", name: "PEITO DE PERU", unit: "KG" },
  { code: "3186", name: "PRESUNTO", unit: "KG" },
  { code: "114513", name: "PURE DE BATATA", unit: "UN" },
  { code: "120051", name: "QUEIJO CATUPIRY", unit: "KG" },
  { code: "120049", name: "QUEIJO MUSSARELA", unit: "KG" },
  { code: "120246", name: "QUEIJO PARMESAO RALADO", unit: "KG" },
  { code: "125618", name: "RECHEIO DE CAMARAO", unit: "KG" },
  { code: "125617", name: "RECHEIO DE CARNE", unit: "KG" },
  { code: "125619", name: "RECHEIO DE CHARQUE", unit: "KG" },
  { code: "125616", name: "RECHEIO DE FRANGO", unit: "KG" },
  { code: "3292", name: "SAL", unit: "KG" },
  { code: "120020", name: "TEMPERO MISTO (COMINHO)", unit: "KG" },
  { code: "34289", name: "TRIGO PARA KIBE", unit: "KG" },
  { code: "45520", name: "UNTAFORMA", unit: "L" },
];
