const listaProducaoBolos = [
  { code: "120010", name: "ACUCAR PRODUÇAO", unit: "KG" },
  { code: "121288", name: "AMEIXA SECA", unit: "KG" },
  { code: "120013", name: "CHOCOLATE EM PO", unit: "UN" },
  { code: "55826", name: "COCO SECO PRODUCAO", unit: "UN" },
  { code: "126351", name: "ESSENCIA COCO", unit: "UN" },
  { code: "120423", name: "FARINHA DE TRIGO", unit: "KG" },
  { code: "33428", name: "FERMENTO PO QUIMICO", unit: "KG" },
  { code: "112450", name: "FRUTAS CRISTALIZADAS", unit: "KG" },
  { code: "120060", name: "GRANULADO", unit: "UN" },
  { code: "124785", name: "HORTI BABANA PRATA", unit: "KG" },
  { code: "120031", name: "HORTI CENOURA", unit: "KG" },
  { code: "120066", name: "HORTI LIMAO", unit: "KG" },
  { code: "111175", name: "HORTI MARACUJA", unit: "KG" },
  { code: "120046", name: "LEITE CONDENSADO", unit: "KG" },
  { code: "120240", name: "LEITE UHT", unit: "L" },
  { code: "119149", name: "MARGARINA VEGETAL", unit: "KG" },
  { code: "103244", name: "MASSA DE MACAXEIRA", unit: "KG" },
  { code: "56298", name: "MASSA DE PUBA", unit: "KG" },
  { code: "122139", name: "MISTURA P/BOLO SABOR NEUTRO", unit: "KG" },
  { code: "120024", name: "OLEO DE SOJA", unit: "LT" },
  { code: "113901", name: "OVO", unit: "UN" },
  { code: "120246", name: "QUEIJO PARMESAO RALADO", unit: "KG" },
  { code: "125524", name: "REFRESCO EM PO DE LARANJA", unit: "UN" },
  { code: "125533", name: "REFRESCO EM PO DE LIMAO", unit: "UN" },
  { code: "120740", name: "REFRESCO EM PO DE MARACUJA", unit: "UN" },
  { code: "45520", name: "UNTAFORMA", unit: "L" },
];
